site_name: Puhuri Documentation
theme:
  name: material
  favicon: assets/favicon.png
  features:
    - navigation.indexes
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
nav:
    - 'index.md'
    - About:
      - 'architecture.md'
      - 'branding.md'
      - 'documents.md'
      - 'terminology.md'
      - 'environments.md'
    - Resource Allocators:
      - 'resource-allocators.md'
      - API Guide:
          - 'API guide/authentication.md'
          - 'API guide/project.md'
          - 'API guide/project-permissions.md'
          - 'API guide/resource-allocation-management.md'
    - 'notifications.md'
    - IdP Integration:
        - 'idp_integration/index.md'
        - eduGAIN integration: idp_integration/requirements-edugain.md
        - Direct integration: idp_integration/requirements-direct.md
        - Attributes: idp_integration/attributes.md
    - 'service-providers.md'

