site_name: Puhuri Documentation
theme:
  name: material
  favicon: assets/favicon.png
  features:
    - navigation.indexes
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - admonition
nav:
  - "index.md"
  - About:
      - "architecture.md"
      - "branding.md"
      - "terminology.md"
      - "environments.md"
      - Documents:
          - "ddocuments/statistics_pp.md"
          - "ddocuments/statistics_tos.md"
  - Resource Allocators:
      - "resource-allocators.md"
      - "integration-with-puhuri-aai.md"
      - API Guide:
          - "API guide/common.md"
          - "API guide/authentication.md"
          - "API guide/project.md"
          - "API guide/project-permissions.md"
          - "API guide/resource-allocation-management.md"
  - Service Providers:
      - "service-providers.md"
      - SDK Guide:
          - "SDK guide/initial-setup.md"
          - "SDK guide/allocation-management-sp.md"
  - Puhuri Portal:
      - User Guide (Dedicated):
          - "puhuri_portal/user_guide_dedicated/organization_and_project_management.md"
          - "puhuri_portal/user_guide_dedicated/inviting_members.md"
          - "puhuri_portal/user_guide_dedicated/project_modification.md"
          - "puhuri_portal/user_guide_dedicated/project_approval.md"
      - User Guide (Shared):
          - "puhuri_portal/user_guide_shared/organization_and_project_management_shared.md"
          - "puhuri_portal/user_guide_shared/membership_management_shared.md"
          - "puhuri_portal/user_guide_shared/project_modification_shared.md"
          - "puhuri_portal/user_guide_shared/project_approval_shared.md"
      - "puhuri_portal/notifications.md"
  - IdP Integration:
      - "idp_integration/index.md"
      - eduGAIN integration: idp_integration/requirements-edugain.md
      - Direct integration: idp_integration/requirements-direct.md
      - Attributes: idp_integration/attributes.md
      - Use cases:
          - National Portal and LUMI: idp_integration/use-cases/national-portal-integration.md
